// Abstract Class is overriden

public class AbstractDemo extends Games{
     public override void basketball(Integer bbplayers) {
        System.debug(bbplayers);
    }
    public override void tt(Integer ttplayers) {
        System.debug(ttplayers);
    }
    
    /* public override void football(Integer fbplayers)
    {
      
        System.debug('Total no of players inFootball are '+fbplayers );
    }*/
    
}