public with sharing class AcountPageController {

    public Integer noOfRecords  {get; set;}
    public Integer size         {get; set;}
    public ApexPages.StandardSetController setCon {
        get {
            if(setCon == null) {
                size = 15;
                String queryString = 'Select Name, Type, BillingCity, BillingState, BillingCountry from Account order by Name';
                setCon = new ApexPages.StandardSetController(Database.getQueryLocator(queryString));
                setCon.setPageSize(size);
                noOfRecords = setCon.getResultSize();
            }
            return setCon;
        } set;
    }

    public List<Account> getAccounts() {
        List<Account> accList = new List<Account>();
        for(Account a : (List<Account>)setCon.getRecords())
            accList.add(a);
        return accList;
    }

    public pageReference refresh() {
        setCon = null;
        getAccounts();
        setCon.setPageNumber(1);
        return null;
    }

}